name: Build and Deploy
on:
  push:
    branches:
      - dev
      - qa

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: Restore & Build .Net Core solution
        run: |
          dotnet build source/DevSecOpsOne.Api/DevSecOpsOne.Api.csproj 
